import { Patient } from "../Types";

interface Ward {
    id: number;
    name: string;
    patients: Patient[];
}
export const dummyPatients : Ward[] = [
    {
      id: 1,
      name: "General Ward",
      patients: [
        {
          id: 1,
          name: "John Doe",
          bed: 1,
          gender: "Male",
          age: 45,
          email: "john.doe@example.com",
          bloodtype: "A+",
          contact: "123-456-7890",
          status: "Occupied",
          appointType: "OPD",
          appointmentDate: new Date("2024-09-10"),
        },
        {
          id: 2,
          name: "Jane Smith",
          bed: 2,
          gender: "Female",
          age: 32,
          email: "jane.smith@example.com",
          bloodtype: "O+",
          contact: "098-765-4321",
          status: "Occupied",
          appointType: "Emergency",
          appointmentDate: new Date("2024-09-12"),
        },
        {
          id: 3,
          name: "Alice Green",
          bed: 3,
          gender: "Female",
          age: 27,
          email: "alice.green@example.com",
          bloodtype: "B+",
          contact: "123-123-1234",
          status: "Billing",
          appointType: "OPD",
          appointmentDate: new Date("2024-09-15"),
        },
        {
          id: 4,
          name: "Bob Brown",
          bed: 4,
          gender: "Male",
          age: 40,
          email: "bob.brown@example.com",
          bloodtype: "AB-",
          contact: "555-555-5555",
          status: "Billing",
          appointType: "IPD",
          appointmentDate: new Date("2024-09-16"),
        },
      ],
    },
    {
      id: 2,
      name: "ICU Ward",
      patients: [
        {
          id: 5,
          name: "David White",
          bed: 1,
          gender: "Male",
          age: 50,
          email: "david.white@example.com",
          bloodtype: "A-",
          contact: "987-654-3210",
          status: "Occupied",
          appointType: "Emergency",
          appointmentDate: new Date("2024-09-14"),
        },
        {
          id: 6,
          name: "Sara Black",
          bed: 2,
          gender: "Female",
          age: 38,
          email: "sara.black@example.com",
          bloodtype: "O-",
          contact: "456-789-1230",
          status: "Billing",
          appointType: "OPD",
          appointmentDate: new Date("2024-09-13"),
        },
        {
          id: 7,
          name: "Tom Blue",
          bed: 3,
          gender: "Male",
          age: 60,
          email: "tom.blue@example.com",
          bloodtype: "B-",
          contact: "321-654-9870",
          status: "Billing",
          appointType: "IPD",
          appointmentDate: new Date("2024-09-18"),
        },
      ],
    },
    {
      id: 3,
      name: "Pediatric Ward",
      patients: [
        {
          id: 8,
          name: "Tim Young",
          bed: 1,
          gender: "Male",
          age: 5,
          email: "tim.young@example.com",
          bloodtype: "O+",
          contact: "555-123-4567",
          status: "Occupied",
          appointType: "IPD",
          appointmentDate: new Date("2024-09-19"),
        },
        {
          id: 9,
          name: "Emily Little",
          bed: 2,
          gender: "Female",
          age: 8,
          email: "emily.little@example.com",
          bloodtype: "A+",
          contact: "444-123-5678",
          status: "Occupied",
          appointType: "OPD",
          appointmentDate: new Date("2024-09-20"),
        },
        {
          id: 10,
          name: "Sam Tiny",
          bed: 3,
          gender: "Male",
          age: 7,
          email: "sam.tiny@example.com",
          bloodtype: "B+",
          contact: "333-123-6789",
          status: "Billing",
          appointType: "IPD",
          appointmentDate: new Date("2024-09-21"),
        },
        {
          id: 11,
          name: "Lily Small",
          bed: 4,
          gender: "Female",
          age: 6,
          email: "lily.small@example.com",
          bloodtype: "AB+",
          contact: "222-123-7890",
          status: "Billing",
          appointType: "OPD",
          appointmentDate: new Date("2024-09-22"),
        },
      ],
    },
    {
      id: 4,
      name: "Maternity Ward",
      patients: [
        {
          id: 12,
          name: "Grace Mother",
          bed: 1,
          gender: "Female",
          age: 30,
          email: "grace.mother@example.com",
          bloodtype: "O+",
          contact: "123-987-6543",
          status: "Occupied",
          appointType: "Emergency",
          appointmentDate: new Date("2024-09-23"),
        },
        {
          id: 13,
          name: "Anna Expectant",
          bed: 2,
          gender: "Female",
          age: 28,
          email: "anna.expectant@example.com",
          bloodtype: "A+",
          contact: "321-654-7890",
          status: "Occupied",
          appointType: "IPD",
          appointmentDate: new Date("2024-09-24"),
        },
        {
          id: 14,
          name: "Eva Newborn",
          bed: 3,
          gender: "Female",
          age: 0,
          email: "eva.newborn@example.com",
          bloodtype: "B+",
          contact: "111-123-4567",
          status: "Billing",
          appointType: "IPD",
          appointmentDate: new Date("2024-09-25"),
        },
      ],
    },
    {
      id: 5,
      name: "Surgical Ward",
      patients: [
        {
          id: 15,
          name: "Liam Surgery",
          bed: 1,
          gender: "Male",
          age: 40,
          email: "liam.surgery@example.com",
          bloodtype: "O-",
          contact: "654-987-3210",
          status: "Occupied",
          appointType: "Emergency",
          appointmentDate: new Date("2024-09-26"),
        },
        {
          id: 16,
          name: "Sophia Cut",
          bed: 2,
          gender: "Female",
          age: 35,
          email: "sophia.cut@example.com",
          bloodtype: "AB+",
          contact: "987-321-6540",
          status: "Occupied",
          appointType: "IPD",
          appointmentDate: new Date("2024-09-27"),
        },
        {
          id: 17,
          name: "Jake Stitches",
          bed: 3,
          gender: "Male",
          age: 45,
          email: "jake.stitches@example.com",
          bloodtype: "B-",
          contact: "432-123-8765",
          status: "Billing",
          appointType: "OPD",
          appointmentDate: new Date("2024-09-28"),
        },
      ],
    },
  ];